apiVersion: v1
kind: Secret
metadata:
  name: {{ include "todo-chatbot.fullname" . }}-secrets
  labels:
    {{- include "todo-chatbot.labels" . | nindent 4 }}
type: Opaque
stringData:
  cohere-api-key: {{ .Values.backend.secrets.cohereApiKey | quote }}
  better-auth-secret: {{ .Values.backend.secrets.betterAuthSecret | quote }}
