apiVersion: v1
kind: Secret
metadata:
  name: todo-app-secrets
  namespace: default
type: Opaque
stringData:
  COHERE_API_KEY: ${COHERE_API_KEY}

  better-auth-secret: "ssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssssss"
