apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  namespace: default
  labels:
    app: todo-app
    component: backend
spec:
  type: NodePort
  ports:
  - port: 8000
    targetPort: http
    protocol: TCP
    name: http
    nodePort: 30800
  selector:
    app: todo-app
    component: backend
